apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  labels:
    name: prometheus-config
data:
  prometheus.yaml: |
    global:
      scrape_interval: 15s

    scrape_configs:
      - job_name: 'user-service-dev'
        metrics_path: /user-service/actuator/prometheus
        static_configs:
          - targets: ["${API_GATEWAY_IP_DEV}:8080"]

      - job_name: 'user-service-stage'
        metrics_path: /user-service/actuator/prometheus
        static_configs:
          - targets: ["${API_GATEWAY_IP_STAGE}:8080"]
