apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: proxy-client
  name: proxy-client
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: proxy-client
  template:
    metadata:
      labels:
        io.kompose.service: proxy-client
      annotations:
        kompose.cmd: kompose convert -f compose.yml -o k8s-manifests/
        kompose.version: 1.36.0 (ae2a39403)
    spec:
      automountServiceAccountToken: false
      containers:
        - env:
            - name: SPRING_CONFIG_IMPORT
              value: optional:configserver:http://cloud-config:9296/
            - name: EUREKA_INSTANCE_HOSTNAME
              value: proxy-client
          envFrom:
            - configMapRef:
                name: common-environment-variables
          name: proxy-client
          image: ${ACR_NAME}.azurecr.io/proxy-client:dev
          ports:
            - containerPort: 8900
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
              ephemeral-storage: "768Mi"
            limits:
              memory: "512Mi"
              cpu: "500m"
              ephemeral-storage: "1Gi"
      restartPolicy: Always

---
apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f compose.yml -o k8s-manifests/
    kompose.version: 1.36.0 (ae2a39403)
  labels:
    io.kompose.service: proxy-client
  name: proxy-client
spec:
  ports:
    - name: "8900"
      port: 8900
      targetPort: 8900
  selector:
    io.kompose.service: proxy-client