apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f compose.yml -o k8s-manifests/
    kompose.version: 1.36.0 (ae2a39403)
  labels:
    io.kompose.service: service-discovery
  name: service-discovery
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: service-discovery
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f compose.yml -o k8s-manifests/
        kompose.version: 1.36.0 (ae2a39403)
      labels:
        io.kompose.service: service-discovery
    spec:
      automountServiceAccountToken: false
      containers:
        - env:
            - name: EUREKA_INSTANCE
              value: service-discovery.dev.svc.cluster.local
            - name: EUREKA_INSTANCE_HOSTNAME
              value: service-discovery
          envFrom:
            - configMapRef:
                name: common-environment-variables
          image: ${ACR_NAME}.azurecr.io/service-discovery:dev
          name: service-discovery
          ports:
            - containerPort: 8761
              protocol: TCP
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
              ephemeral-storage: "512Mi"
            limits:
              memory: "512Mi"
              cpu: "500m"
              ephemeral-storage: "1Gi"
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8761
            initialDelaySeconds: 120
            periodSeconds: 15
            timeoutSeconds: 3
            failureThreshold: 6
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8761
            initialDelaySeconds: 150
            periodSeconds: 30
            timeoutSeconds: 3
            failureThreshold: 3
      restartPolicy: Always

---
apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f compose.yml -o k8s-manifests/
    kompose.version: 1.36.0 (ae2a39403)
  labels:
    io.kompose.service: service-discovery
  name: service-discovery
spec:
  type: LoadBalancer
  ports:
    - name: "8761"
      port: 8761
      targetPort: 8761
  selector:
    io.kompose.service: service-discovery