name: Promote and Cleanup Secrets

on:
  workflow_dispatch:

jobs:
  promote-secrets:
    runs-on: ubuntu-latest

    env:
      ORG: microservices-final-project

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install GitHub CLI
        run: sudo apt-get update && sudo apt-get install gh -y

      - name: Authenticate with GitHub CLI
        run: |
          if [ -z "${{ secrets.GH_PAT }}" ]; then
            echo "ERROR: GH_PAT secret is not set"
            exit 1
          fi
          echo "${{ secrets.GH_PAT }}" | gh auth login --with-token
          gh auth status

      - name: Set Organization Secrets for public repos
        run: |
          secrets_list=(
            "GH_PAT:${{ secrets.GH_PAT }}"
          )

          for item in "${secrets_list[@]}"; do
            secret_name="${item%%:*}"
            secret_value="${item#*:}"
            
            if [ -z "$secret_value" ]; then
              echo "WARNING: Secret $secret_name is empty or not found"
              continue
            fi
            
            echo "Setting org secret: $secret_name with public visibility"
            echo "$secret_value" | gh secret set "$secret_name" --org "$ORG" --visibility "all"
          done
